### ISSUE TITLE
Require a new UI theme align to hackoberfest 2022 theme

### ISSUE THREAD

**Issue by genialkartik** [genialkartik/hacktoberfest-checker#254]

**Comment by seanysean** [comment]
Hello! I would like to give this a try.

**Comment by seanysean** [comment]
This is the progress I have made so far, what should the default image be for the `.avatarBox`? I will probably make further changes on Monday. Don't worry about the contributor avatars section, I just hit the rate limit.
![image](https://user-images.githubusercontent.com/24863887/194729399-cc279388-a716-427f-b0ed-5d0f6a63886b.png)

**Comment by genialkartik** [comment]
Thanks, @seanysean , That looks really fantastic. 
About the avatar, just keep the new hacktoberfest Icon as the new avatar as default and replace the avatar with the user's GitHub avatar once the user is been fetched from Github API.

Good work so far, keep it going.

**Comment by seanysean** [comment]
Thank you!
I've added the Hacktoberfest badge logo as the default avatar and the pull request is ready for review. Let me know if there are any adjustments you would like me to make 👍
