### ISSUE TITLE
Hacktoberfest 2021 theme

### ISSUE THREAD

**Issue by fleshdroppp** [genialkartik/hacktoberfest-checker#28]
Hacktoberfest 2021 start soon, so I would like to make a new app theme according to site of Hacktoberfest

**Comment by micahlt** [comment]
I could also contribute to this!

**Comment by genialkartik** [comment]
That's great!! make sure to clone the latest code from the repo itself and contribute! 🌟

**Comment by genialkartik** [comment]
Thanks for your contributions guys!!

Special thanks to @harshndroid
Counting your contributions really valuable to the project. I would like to invite you as a maintainer of this project.
If interested, do let me know and also feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/genial-kartik/)
