### ISSUE TITLE
Hacktoberfest contribution 2021

### ISSUE THREAD

**Issue by genialkartik** [genialkartik/hacktoberfest-checker#37]
We created this project to check the user's PR status as well as the eligibility of the PRs .

Policies and Rules to contribute wrt Guidelines & Policies of the Hacktoberfest have been changed since last year.

find new updates here or on hacktoberfest.digitalocean.com.

**Comment by kushalsng** [comment]
what do I contribute here as you haven't mentioned any task?

**Comment by genialkartik** [comment]
@kushalsng you could try anything interesting!!

**Comment by kushalsng** [comment]
after installing packages and running npm start, 
Cannot find file: 'home.css' does not match the corresponding name on disk: '.\src\components\assets\css\Css'.

this error is occuring while starting on localhost.
Is this a bug in code or I am doing something wrong?

**Comment by genialkartik** [comment]
we have two Css files (Css & css)in the project.. I forgot to remove Css. will fix in next update.
You could also fix it in your local host, if you want to.

**Comment by genialkartik** [comment]
Thanks to all the contributors who added their valuable contributions to this project.
Closing this issue with the best wishes in your developer journeys ahead. 🎉
