### ISSUE TITLE
Single command to start both servers

### ISSUE THREAD

**Issue by lakshyaTaragi** [genialkartik/hacktoberfest-checker#7]
**Is your feature request related to a problem? Please describe.**
Use a single npm command to start both frontend and backend servers simultaneously.

**Describe the solution you'd like**
Use a package like npm-run-all to combine both commands

**Comment by eLeontev** [comment]
I will take care

**Comment by eLeontev** [comment]
@lakshyaTaragi  hi, the PR is done, please review

**Comment by genialkartik** [comment]
Thank you @lakshyaTaragi and @eLeontev , 
Actually, I initiated this project earlier with all backend functioning, and our lazy, front-end developers started in it lately.
Which ended up with two different code sources and dir and hence the package.json .

But thanks to @eLeontev to make it work with single command [#9](https://github.com/genialkartik/hacktoberfest-checker/pull/9)
Also, thanks @lakshyaTaragi to go through the project and to point the thing out.
