### ISSUE TITLE
Broken avatar image and infinite loader when invalid username

### ISSUE THREAD

**Issue by saraogipraveen** [genialkartik/hacktoberfest-checker#8]
When the username is not a valid Github username it shows a broken avatar with infinite loader. 

![image](https://user-images.githubusercontent.com/16433473/97270789-b8fff100-1855-11eb-8e36-ae78e3b1d54e.png)

**Comment by genialkartik** [comment]
thank you @saraogipraveen to point the thing out.
@abhimittal342 has fixed the same and I'll update the same in production soon.
